# NBA Championship Database - DML

In [119]:
#import all necessary packages and modules
import pandas as pd
import sqlite3

In [120]:
# standard imports for %sql magic
%load_ext sql

# connect to %sql database connection, has been created in DDL notebook 
%sql sqlite:///nba_db.db

The sql extension is already loaded. To reload it, use:
  %reload_ext sql

'Connected: None@nba_db.db'

## Insert data into our main data table 
_The following insert statements were copied from sqlite3 commands to extract the data from our csv_

In [121]:
%%sql
INSERT INTO NBAData VALUES('1980','Lakers','LAL','1','1','1','240','0','13','12','31','109');
INSERT INTO NBAData VALUES('1980','Lakers','LAL','2','0','1','240','0','8','15','37','104');
INSERT INTO NBAData VALUES('1980','Lakers','LAL','3','1','0','240','0','23','22','34','111');
INSERT INTO NBAData VALUES('1980','Lakers','LAL','4','0','0','240','0','14','18','31','102');
INSERT INTO NBAData VALUES('1980','Lakers','LAL','5','1','1','240','0','26','19','37','108');
INSERT INTO NBAData VALUES('1980','Lakers','LAL','6','1','0','240','0','33','17','35','123');
INSERT INTO NBAData VALUES('1981','Celtics','BOS','1','1','1','240','0','16','25','29','98');
INSERT INTO NBAData VALUES('1981','Celtics','BOS','2','0','1','240','0','8','14','34','90');
INSERT INTO NBAData VALUES('1981','Celtics','BOS','3','1','0','240','2','12','16','28','94');
INSERT INTO NBAData VALUES('1981','Celtics','BOS','4','0','0','240','0','16','17','30','86');
INSERT INTO NBAData VALUES('1981','Celtics','BOS','5','1','1','240','0','27','19','35','109');
INSERT INTO NBAData VALUES('1981','Celtics','BOS','6','1','0','240','1','15','9','28','102');
INSERT INTO NBAData VALUES('1982','Lakers','LAL','1','1','0','240','0','26','19','31','124');
INSERT INTO NBAData VALUES('1982','Lakers','LAL','2','0','0','240','0','24','17','22','94');
INSERT INTO NBAData VALUES('1982','Lakers','LAL','3','1','1','240','1','28','17','31','129');
INSERT INTO NBAData VALUES('1982','Lakers','LAL','4','1','1','240','0','21','16','33','111');
INSERT INTO NBAData VALUES('1982','Lakers','LAL','5','0','0','240','0','8','26','23','102');
INSERT INTO NBAData VALUES('1982','Lakers','LAL','6','1','1','240','0','20','15','34','114');
INSERT INTO NBAData VALUES('1983','Sixers','PHI','1','1','1','240','0','23','21','32','113');
INSERT INTO NBAData VALUES('1983','Sixers','PHI','2','1','1','240','0','23','16','28','103');
INSERT INTO NBAData VALUES('1983','Sixers','PHI','3','1','0','240','0','21','22','32','111');
INSERT INTO NBAData VALUES('1983','Sixers','PHI','4','1','0','240','0','31','13','28','115');
INSERT INTO NBAData VALUES('1984','Celtics','BOS','1','1','1','240','1','28','12','30','115');
INSERT INTO NBAData VALUES('1984','Celtics','BOS','2','0','1','265','0','34','20','30','124');
INSERT INTO NBAData VALUES('1984','Celtics','BOS','3','0','0','240','2','22','17','27','104');
INSERT INTO NBAData VALUES('1984','Celtics','BOS','4','1','0','265','2','31','27','25','129');
INSERT INTO NBAData VALUES('1984','Celtics','BOS','5','1','1','240','3','28','13','38','121');
INSERT INTO NBAData VALUES('1984','Celtics','BOS','6','0','0','240','1','29','13','28','108');
INSERT INTO NBAData VALUES('1984','Celtics','BOS','7','1','1','240','0','43','20','32','111');
INSERT INTO NBAData VALUES('1985','Lakers','LAL','1','0','0','240','2','14','8','27','114');
INSERT INTO NBAData VALUES('1985','Lakers','LAL','2','1','0','240','1','20','14','35','109');
INSERT INTO NBAData VALUES('1985','Lakers','LAL','3','1','1','240','4','28','13','36','136');
INSERT INTO NBAData VALUES('1985','Lakers','LAL','4','0','1','240','1','24','9','31','105');
INSERT INTO NBAData VALUES('1985','Lakers','LAL','5','1','1','240','0','20','10','29','120');
INSERT INTO NBAData VALUES('1985','Lakers','LAL','6','1','0','240','0','25','12','32','111');
INSERT INTO NBAData VALUES('1986','Celtics','BOS','1','1','1','240','1','17','10','32','112');
INSERT INTO NBAData VALUES('1986','Celtics','BOS','2','1','1','240','4','23','14','29','117');
INSERT INTO NBAData VALUES('1986','Celtics','BOS','3','0','0','240','1','19','22','31','104');
INSERT INTO NBAData VALUES('1986','Celtics','BOS','4','1','0','240','2','14','11','29','106');
INSERT INTO NBAData VALUES('1986','Celtics','BOS','5','0','0','240','1','27','10','27','96');
INSERT INTO NBAData VALUES('1986','Celtics','BOS','6','1','1','240','1','12','23','33','111');
INSERT INTO NBAData VALUES('1987','Lakers','LAL','1','1','1','240','1','15','17','30','126');
INSERT INTO NBAData VALUES('1987','Lakers','LAL','2','1','1','240','6','23','7','26','141');
INSERT INTO NBAData VALUES('1987','Lakers','LAL','3','0','0','240','3','20','8','24','103');
INSERT INTO NBAData VALUES('1987','Lakers','LAL','4','1','0','240','2','23','15','31','107');
INSERT INTO NBAData VALUES('1987','Lakers','LAL','5','0','0','240','4','18','17','23','108');
INSERT INTO NBAData VALUES('1987','Lakers','LAL','6','1','1','240','0','16','13','31','106');
INSERT INTO NBAData VALUES('1988','Lakers','LAL','1','0','1','240','2','25','13','22','93');
INSERT INTO NBAData VALUES('1988','Lakers','LAL','2','1','1','240','3','35','8','35','108');
INSERT INTO NBAData VALUES('1988','Lakers','LAL','3','1','0','240','1','24','5','33','99');
INSERT INTO NBAData VALUES('1988','Lakers','LAL','4','0','0','240','0','28','8','26','86');
INSERT INTO NBAData VALUES('1988','Lakers','LAL','5','0','0','240','1','19','15','16','94');
INSERT INTO NBAData VALUES('1988','Lakers','LAL','6','1','1','240','0','35','13','28','103');
INSERT INTO NBAData VALUES('1988','Lakers','LAL','7','1','1','240','3','19','10','31','108');
INSERT INTO NBAData VALUES('1989','Pistons','DET','1','1','1','240','1','16','9','36','109');
INSERT INTO NBAData VALUES('1989','Pistons','DET','2','1','1','240','1','19','13','22','108');
INSERT INTO NBAData VALUES('1989','Pistons','DET','3','1','0','240','1','27','14','30','114');
INSERT INTO NBAData VALUES('1989','Pistons','DET','4','1','0','240','2','35','9','27','105');
INSERT INTO NBAData VALUES('1990','Pistons','DET','1','1','1','240','3','34','19','35','105');
INSERT INTO NBAData VALUES('1990','Pistons','DET','2','0','1','265','8','15','15','29','105');
INSERT INTO NBAData VALUES('1990','Pistons','DET','3','1','0','240','3','32','10','26','121');
INSERT INTO NBAData VALUES('1990','Pistons','DET','4','1','0','240','7','21','12','27','112');
INSERT INTO NBAData VALUES('1990','Pistons','DET','5','1','0','240','4','14','16','28','92');
INSERT INTO NBAData VALUES('1991','Bulls','CHI','1','0','1','240','1','14','9','30','91');
INSERT INTO NBAData VALUES('1991','Bulls','CHI','2','1','1','240','0','7','11','25','107');
INSERT INTO NBAData VALUES('1991','Bulls','CHI','3','1','0','265','1','21','16','30','104');
INSERT INTO NBAData VALUES('1991','Bulls','CHI','4','1','0','240','1','12','9','29','97');
INSERT INTO NBAData VALUES('1991','Bulls','CHI','5','1','0','240','2','22','10','27','108');
INSERT INTO NBAData VALUES('1992','Bulls','CHI','1','1','1','240','7','15','16','28','122');
INSERT INTO NBAData VALUES('1992','Bulls','CHI','2','0','1','265','5','17','10','31','104');
INSERT INTO NBAData VALUES('1992','Bulls','CHI','3','1','0','240','1','19','9','33','94');
INSERT INTO NBAData VALUES('1992','Bulls','CHI','4','0','0','240','4','14','7','26','88');
INSERT INTO NBAData VALUES('1992','Bulls','CHI','5','1','0','240','2','37','10','24','119');
INSERT INTO NBAData VALUES('1992','Bulls','CHI','6','1','1','240','6','15','9','22','97');
INSERT INTO NBAData VALUES('1993','Bulls','CHI','1','1','0','240','3','11','10','31','100');
INSERT INTO NBAData VALUES('1993','Bulls','CHI','2','1','0','240','3','18','17','26','111');
INSERT INTO NBAData VALUES('1993','Bulls','CHI','3','0','1','315','5','6','27','32','121');
INSERT INTO NBAData VALUES('1993','Bulls','CHI','4','1','1','240','3','20','12','30','111');
INSERT INTO NBAData VALUES('1993','Bulls','CHI','5','0','1','240','8','16','8','27','98');
INSERT INTO NBAData VALUES('1993','Bulls','CHI','6','1','0','240','10','11','12','27','99');
INSERT INTO NBAData VALUES('1994','Rockets','HOU','1','1','1','240','4','19','12','37','85');
INSERT INTO NBAData VALUES('1994','Rockets','HOU','2','0','1','240','6','13','17','21','83');
INSERT INTO NBAData VALUES('1994','Rockets','HOU','3','1','0','240','6','27','14','33','93');
INSERT INTO NBAData VALUES('1994','Rockets','HOU','4','0','0','240','6','14','7','26','82');
INSERT INTO NBAData VALUES('1994','Rockets','HOU','5','0','0','240','6','12','15','27','84');
INSERT INTO NBAData VALUES('1994','Rockets','HOU','6','1','1','240','5','17','6','32','86');
INSERT INTO NBAData VALUES('1994','Rockets','HOU','7','1','1','240','4','18','3','30','90');
INSERT INTO NBAData VALUES('1995','Rockets','HOU','1','1','0','265','14','18','9','32','120');
INSERT INTO NBAData VALUES('1995','Rockets','HOU','2','1','0','240','5','34','9','29','117');
INSERT INTO NBAData VALUES('1995','Rockets','HOU','3','1','1','240','7','21','11','35','106');
INSERT INTO NBAData VALUES('1995','Rockets','HOU','4','1','1','240','11','22','15','33','113');
INSERT INTO NBAData VALUES('1996','Bulls','CHI','1','1','1','240','7','26','17','23','107');
INSERT INTO NBAData VALUES('1996','Bulls','CHI','2','1','1','240','4','28','20','25','92');
INSERT INTO NBAData VALUES('1996','Bulls','CHI','3','1','0','240','7','25','10','23','108');
INSERT INTO NBAData VALUES('1996','Bulls','CHI','4','0','0','240','6','16','15','21','86');
INSERT INTO NBAData VALUES('1996','Bulls','CHI','5','0','0','240','3','17','15','25','78');
INSERT INTO NBAData VALUES('1996','Bulls','CHI','6','1','0','240','9','16','24','27','87');
INSERT INTO NBAData VALUES('1997','Bulls','CHI','1','1','1','240','6','10','10','26','84');
INSERT INTO NBAData VALUES('1997','Bulls','CHI','2','1','1','240','6','27','11','30','97');
INSERT INTO NBAData VALUES('1997','Bulls','CHI','3','0','0','240','12','15','8','27','93');
INSERT INTO NBAData VALUES('1997','Bulls','CHI','4','0','0','240','4','5','10','28','73');
INSERT INTO NBAData VALUES('1997','Bulls','CHI','5','1','0','240','6','20','10','32','90');
INSERT INTO NBAData VALUES('1997','Bulls','CHI','6','1','1','240','5','23','15','35','90');
INSERT INTO NBAData VALUES('1998','Bulls','CHI','1','0','0','265','3','14','9','32','85');
INSERT INTO NBAData VALUES('1998','Bulls','CHI','2','1','0','240','3','22','18','18','93');
INSERT INTO NBAData VALUES('1998','Bulls','CHI','3','1','1','240','4','18','11','39','96');
INSERT INTO NBAData VALUES('1998','Bulls','CHI','4','1','1','240','5','27','17','27','86');
INSERT INTO NBAData VALUES('1998','Bulls','CHI','5','0','1','240','7','16','13','20','81');
INSERT INTO NBAData VALUES('1998','Bulls','CHI','6','1','0','240','4','15','5','17','87');
INSERT INTO NBAData VALUES('1999','Spurs','SAS','1','1','1','240','6','19','4','33','89');
INSERT INTO NBAData VALUES('1999','Spurs','SAS','2','1','1','240','2','24','5','36','80');
INSERT INTO NBAData VALUES('1999','Spurs','SAS','3','0','0','240','5','18','10','26','81');
INSERT INTO NBAData VALUES('1999','Spurs','SAS','4','1','0','240','3','23','14','35','96');
INSERT INTO NBAData VALUES('1999','Spurs','SAS','5','1','0','240','5','19','9','31','78');
INSERT INTO NBAData VALUES('2000','Lakers','LAL','1','1','1','240','3','11','14','34','104');
INSERT INTO NBAData VALUES('2000','Lakers','LAL','2','1','1','240','7','32','11','36','111');
INSERT INTO NBAData VALUES('2000','Lakers','LAL','3','0','0','240','7','8','8','25','91');
INSERT INTO NBAData VALUES('2000','Lakers','LAL','4','1','0','265','4','20','14','28','120');
INSERT INTO NBAData VALUES('2000','Lakers','LAL','5','0','0','240','4','11','13','21','87');
INSERT INTO NBAData VALUES('2000','Lakers','LAL','6','1','1','240','10','20','13','31','116');
INSERT INTO NBAData VALUES('2001','Lakers','LAL','1','0','1','265','6','15','16','28','101');
INSERT INTO NBAData VALUES('2001','Lakers','LAL','2','1','1','240','4','18','15','37','98');
INSERT INTO NBAData VALUES('2001','Lakers','LAL','3','1','0','240','4','22','10','30','96');
INSERT INTO NBAData VALUES('2001','Lakers','LAL','4','1','0','240','10','18','12','31','100');
INSERT INTO NBAData VALUES('2001','Lakers','LAL','5','1','0','240','12','32','14','33','108');
INSERT INTO NBAData VALUES('2002','Lakers','LAL','1','1','1','240','1','32','17','33','99');
INSERT INTO NBAData VALUES('2002','Lakers','LAL','2','1','1','240','9','19','12','35','106');
INSERT INTO NBAData VALUES('2002','Lakers','LAL','3','1','0','240','8','24','7','33','106');
INSERT INTO NBAData VALUES('2002','Lakers','LAL','4','1','0','240','11','28','7','32','113');
INSERT INTO NBAData VALUES('2003','Spurs','SAS','1','1','1','240','4','19','10','37','101');
INSERT INTO NBAData VALUES('2003','Spurs','SAS','2','0','1','240','5','14','14','29','85');
INSERT INTO NBAData VALUES('2003','Spurs','SAS','3','1','0','240','5','23','9','29','84');
INSERT INTO NBAData VALUES('2003','Spurs','SAS','4','0','0','240','4','20','22','31','76');
INSERT INTO NBAData VALUES('2003','Spurs','SAS','5','1','0','240','3','24','8','31','93');
INSERT INTO NBAData VALUES('2003','Spurs','SAS','6','1','1','240','3','17','11','44','88');
INSERT INTO NBAData VALUES('2004','Pistons','DET','1','1','0','240','6','21','9','27','87');
INSERT INTO NBAData VALUES('2004','Pistons','DET','2','0','0','265','6','21','19','27','91');
INSERT INTO NBAData VALUES('2004','Pistons','DET','3','1','1','240','5','21','15','36','88');
INSERT INTO NBAData VALUES('2004','Pistons','DET','4','1','1','240','2','28','9','36','88');
INSERT INTO NBAData VALUES('2004','Pistons','DET','5','1','1','240','2','28','20','30','100');
INSERT INTO NBAData VALUES('2005','Spurs','SAS','1','1','1','240','4','12','15','34','84');
INSERT INTO NBAData VALUES('2005','Spurs','SAS','2','1','1','240','11','28','9','27','97');
INSERT INTO NBAData VALUES('2005','Spurs','SAS','3','0','0','240','8','13','10','27','79');
INSERT INTO NBAData VALUES('2005','Spurs','SAS','4','0','0','240','5','14','12','32','71');
INSERT INTO NBAData VALUES('2005','Spurs','SAS','5','1','0','265','8','12','19','26','96');
INSERT INTO NBAData VALUES('2005','Spurs','SAS','6','0','1','240','8','16','13','30','86');
INSERT INTO NBAData VALUES('2005','Spurs','SAS','7','1','1','240','7','16','8','30','81');
INSERT INTO NBAData VALUES('2006','Heat','MIA','1','0','0','240','5','7','12','33','80');
INSERT INTO NBAData VALUES('2006','Heat','MIA','2','0','0','240','7','20','8','24','85');
INSERT INTO NBAData VALUES('2006','Heat','MIA','3','1','1','240','4','20','16','33','98');
INSERT INTO NBAData VALUES('2006','Heat','MIA','4','1','1','240','7','23','6','42','98');
INSERT INTO NBAData VALUES('2006','Heat','MIA','5','1','1','265','7','32','7','26','101');
INSERT INTO NBAData VALUES('2006','Heat','MIA','6','1','0','240','2','23','14','42','95');
INSERT INTO NBAData VALUES('2007','Spurs','SAS','1','1','1','240','6','11','13','30','85');
INSERT INTO NBAData VALUES('2007','Spurs','SAS','2','1','1','240','8','21','12','34','103');
INSERT INTO NBAData VALUES('2007','Spurs','SAS','3','1','0','240','10','9','7','34','75');
INSERT INTO NBAData VALUES('2007','Spurs','SAS','4','1','0','240','5','20','11','34','83');
INSERT INTO NBAData VALUES('2008','Celtics','BOS','1','1','1','240','6','28','10','36','98');
INSERT INTO NBAData VALUES('2008','Celtics','BOS','2','1','1','240','9','27','10','27','108');
INSERT INTO NBAData VALUES('2008','Celtics','BOS','3','0','0','240','8','15','14','31','81');
INSERT INTO NBAData VALUES('2008','Celtics','BOS','4','1','0','240','8','23','6','34','97');
INSERT INTO NBAData VALUES('2008','Celtics','BOS','5','0','0','240','8','24','11','26','98');
INSERT INTO NBAData VALUES('2008','Celtics','BOS','6','1','1','240','13','32','14','34','131');
INSERT INTO NBAData VALUES('2009','Lakers','LAL','1','1','1','240','3','15','15','40','100');
INSERT INTO NBAData VALUES('2009','Lakers','LAL','2','1','1','265','5','24','4','31','101');
INSERT INTO NBAData VALUES('2009','Lakers','LAL','3','0','0','240','8','16','11','16','104');
INSERT INTO NBAData VALUES('2009','Lakers','LAL','4','1','0','265','8','15','10','29','99');
INSERT INTO NBAData VALUES('2009','Lakers','LAL','5','1','0','240','8','21','13','34','99');
INSERT INTO NBAData VALUES('2010','Lakers','LAL','1','1','1','240','4','24','12','30','102');
INSERT INTO NBAData VALUES('2010','Lakers','LAL','2','0','1','240','5','31','10','29','94');
INSERT INTO NBAData VALUES('2010','Lakers','LAL','3','1','0','240','2','21','11','32','91');
INSERT INTO NBAData VALUES('2010','Lakers','LAL','4','0','0','240','7','18','8','26','89');
INSERT INTO NBAData VALUES('2010','Lakers','LAL','5','0','0','240','7','17','16','18','86');
INSERT INTO NBAData VALUES('2010','Lakers','LAL','6','1','1','240','6','17','12','40','89');
INSERT INTO NBAData VALUES('2010','Lakers','LAL','7','1','1','240','4','25','23','30','83');
INSERT INTO NBAData VALUES('2011','Mavericks','DAL','1','0','0','240','9','25','6','30','84');
INSERT INTO NBAData VALUES('2011','Mavericks','DAL','2','1','0','240','6','17','11','30','95');
INSERT INTO NBAData VALUES('2011','Mavericks','DAL','3','0','1','240','8','22','12','30','86');
INSERT INTO NBAData VALUES('2011','Mavericks','DAL','4','1','1','240','4','24','12','29','86');
INSERT INTO NBAData VALUES('2011','Mavericks','DAL','5','1','1','240','13','21','4','22','112');
INSERT INTO NBAData VALUES('2011','Mavericks','DAL','6','1','0','240','11','12','10','30','105');
INSERT INTO NBAData VALUES('2012','Heat','MIA','1','0','0','240','8','14','7','28','94');
INSERT INTO NBAData VALUES('2012','Heat','MIA','2','1','0','240','6','22','11','29','100');
INSERT INTO NBAData VALUES('2012','Heat','MIA','3','1','1','240','4','31','14','31','91');
INSERT INTO NBAData VALUES('2012','Heat','MIA','4','1','1','240','10','18','9','31','104');
INSERT INTO NBAData VALUES('2012','Heat','MIA','5','1','1','240','14','27','8','33','121');
INSERT INTO NBAData VALUES('2012','Heat','MIA','1','0','1','240','8','12','9','37','88');
INSERT INTO NBAData VALUES('2013','Heat','MIA','2','1','1','240','10','11','9','27','103');
INSERT INTO NBAData VALUES('2013','Heat','MIA','3','0','0','240','8','7','9','27','77');
INSERT INTO NBAData VALUES('2013','Heat','MIA','4','1','0','240','4','15','7','34','109');
INSERT INTO NBAData VALUES('2013','Heat','MIA','5','0','0','240','11','19','12','22','104');
INSERT INTO NBAData VALUES('2013','Heat','MIA','6','1','1','265','11','16','12','30','103');
INSERT INTO NBAData VALUES('2013','Heat','MIA','7','1','1','240','12','11','11','32','95');
INSERT INTO NBAData VALUES('2014','Spurs','SAS','1','1','1','240','13','17','5','34','110');
INSERT INTO NBAData VALUES('2014','Spurs','SAS','2','0','1','240','12','12','11','26','96');
INSERT INTO NBAData VALUES('2014','Spurs','SAS','3','1','0','240','9','26','5','24','111');
INSERT INTO NBAData VALUES('2014','Spurs','SAS','4','1','0','240','9','18','12','32','107');
INSERT INTO NBAData VALUES('2014','Spurs','SAS','5','1','1','240','12','18','6','34','104');
INSERT INTO NBAData VALUES('2015','Warriors','GSW','1','1','1','265','10','20','11','37','108');
INSERT INTO NBAData VALUES('2015','Warriors','GSW','2','0','1','265','8','19','10','35','93');
INSERT INTO NBAData VALUES('2015','Warriors','GSW','3','0','0','240','12','7','18','28','91');
INSERT INTO NBAData VALUES('2015','Warriors','GSW','4','1','0','240','12','19','6','38','103');
INSERT INTO NBAData VALUES('2015','Warriors','GSW','5','1','1','240','12','20','11','32','104');
INSERT INTO NBAData VALUES('2015','Warriors','GSW','6','1','0','240','13','18','7','32','105');
INSERT INTO NBAData VALUES('2016','Cavaliers','CLE','1','0','0','240','7','18','15','32','89');
INSERT INTO NBAData VALUES('2016','Cavaliers','CLE','2','0','0','240','5','16','9','25','77');
INSERT INTO NBAData VALUES('2016','Cavaliers','CLE','3','1','1','240','12','12','17','35','120');
INSERT INTO NBAData VALUES('2016','Cavaliers','CLE','4','0','1','240','6','15','16','24','97');
INSERT INTO NBAData VALUES('2016','Cavaliers','CLE','5','1','0','240','10','14','8','33','112');
INSERT INTO NBAData VALUES('2016','Cavaliers','CLE','6','1','1','240','10','25','8','37','115');
INSERT INTO NBAData VALUES('2016','Cavaliers','CLE','7','1','0','240','6','21','9','39','93');
INSERT INTO NBAData VALUES('2017','Warriors','GSW','1','1','1','240','12','11','14','36','113');
INSERT INTO NBAData VALUES('2017','Warriors','GSW','2','1','1','240','18','22','10','43','132');
INSERT INTO NBAData VALUES('2017','Warriors','GSW','3','1','0','240','16','22','8','36','118');
INSERT INTO NBAData VALUES('2017','Warriors','GSW','4','0','0','240','11','27','16','24','116');
INSERT INTO NBAData VALUES('2017','Warriors','GSW','5','1','1','240','14','23','13','29','129');

1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.
1 rows affected.

[]

## Migration
* The following code was used to grab data from a web based csv, which we will grab data from to import and query into our database without downloading the actual file. Once retrieved, the data in formated into a datafram and transferred our sqlite3 database using the .to_sql command

In [151]:
#connect to web based csv file and create dataframe
players = pd.read_csv('https://query.data.world/s/ITKVBzG71Zh6xB8e4tltf0roHnOaQJ')
players_df = pd.DataFrame(players)
players_df.to_sql('PlayerData', sqlite3.connect('nba_db.db'),index=False)

/Users/nastajajohnson/anaconda3/lib/python3.6/site-packages/pandas/core/generic.py:1362: UserWarning: The spaces in these column names will not be changed. In pandas versions < 0.14, spaces were converted to underscores.
  chunksize=chunksize, dtype=dtype)

In [137]:
%%sql
SELECT * from PlayerData limit 10;

Done.

[(1978, 'NOJ', 'Truck Robinson', 26, 82, 3638, 15.7, 0.48100000000000004, None, 0.34, 8.0, 25.8, 17.0, 6.8, 0.9, 1.1, 13.5, 23.3, None, 1.5, 5.0, 6.5, 0.086, None, -1.4, 0.2, -1.2, 0.7, 0.02, 0.066, 20.2, 'robintr01', -1.61, 19780, 82, 0.0, 0.505, 331339, 0.512, -1.73, -1.12, -0.16, -0.37, 2.0, -1.21, '92.00%', -1.12, -1.28, -0.13, -1.3, 2.0, -1.2, 0.6, -1.0, 0.2, -0.7, -0.3, 1.0, -0.8, -0.7, -1.9, 1.1, -0.7, 0.3, -1.5, 1.3, -1.4, 0.2, 0.1, 1.5, 0.1, 0.4, -1.6, 0.9, 44.4, 42.3, -1.3, -1.2, 0.6, 0.6, -1.5, -1.4, 0.2, 0.2, 0.1, 0.1, 0.4, 0.4, '$3,900,000 ', '$3,900,000 ', 3.2, 0.7, 0.6, 1.6, '$8,800,000 ', 0.4, '$2,900,000 ', 1.6, 0.6, 1.1, 1.1, 3.6, 4.0, 26.33, 3.0, 79.0, 225.0, 4.0, 26.0),
 (1978, 'BUF', 'Randy Smith', 29, 82, 3314, 19.1, 0.521, None, 0.326, 3.6, 6.4, 5.0, 22.2, 2.4, 0.2, 12.8, 26.8, None, 6.1, 1.7, 7.9, 0.114, None, 2.8, -1.2, 1.6, 3.0, 0.08900000000000001, 0.025, 23.4, 'smithra01', -3.25, 19805, 82, 0.0, 0.518, 332955, 0.517, 0.52, 0.29, 0.17, -0.19, 1.54, 2.16, '83.70%', 1.81, -1.89, -0.4, 1.8, 2.0, 1.5, 3.1, 0.1, 0.4, 1.9, 0.3, 0.8, 3.4, 2.8, -0.5, 1.1, -0.3, -2.8, 3.1, 1.3, 2.6, 4.0, -1.3, 1.5, -1.1, -0.8, 4.4, 0.8, 40.4, 38.5, 1.8, 1.5, 3.1, 3.1, 3.1, 2.6, 4.0, 4.0, -1.3, -1.1, -0.8, -0.8, '$16,200,000 ', '$16,200,000 ', 2.1, 1.9, 0.73, 2.8, '$14,800,000 ', 2.7, '$14,200,000 ', 8.5, 10.8, -2.3, 7.4, 1.0, 2.0, 29.14, 6.0, 75.0, 180.0, 1.0, 29.0),
 (1978, 'WSB', 'Elvin Hayes', 32, 81, 3246, 17.1, 0.489, None, 0.365, 10.2, 22.7, 16.4, 6.5, 1.3, 2.4, 12.3, 21.6, None, 3.5, 4.8, 8.3, 0.12300000000000001, None, 0.1, 1.2, 1.3, 2.7, 0.052000000000000005, 0.071, 18.9, 'hayesel01', 0.7, 19830, 82, 0.0, 0.506, 336086, 0.51, -1.31, 0.08, -0.14, 0.5, 1.49, 0.76, '81.80%', 0.62, -2.05, 0.58, 1.3, 2.0, 1.1, 2.7, -0.3, 0.2, -0.2, -0.2, 0.8, 0.3, 0.2, 0.4, 1.4, -0.2, 0.3, 0.1, 1.3, 0.1, 1.5, 1.3, 1.5, 1.0, 1.3, -1.2, 0.8, 40.1, 38.2, 1.3, 1.1, 2.7, 2.8, 0.1, 0.1, 1.5, 1.5, 1.3, 1.0, 1.3, 1.3, '$14,200,000 ', '$14,400,000 ', 2.6, 1.9, 0.73, 2.8, '$14,700,000 ', 2.4, '$12,700,000 ', 7.4, 3.9, 3.4, 6.5, 4.2, 4.0, 32.21, 9.0, 81.0, 235.0, 4.0, 32.0),
 (1978, 'BOS', 'Dave Cowens', 29, 77, 3215, 18.6, 0.5329999999999999, None, 0.233, 8.0, 25.6, 17.0, 15.7, 1.4, 1.1, 13.9, 18.8, None, 6.1, 4.8, 10.8, 0.162, None, 1.8, 2.1, 4.0, 4.8, 0.091, 0.071, 16.2, 'cowenda01', -1.68, 19830, 82, 0.0, 0.505, 332440, 0.5, 2.36, -0.49, 0.12, 1.06, 1.68, 4.61, '81.10%', 3.74, -0.9, -0.22, 4.4, 2.0, 3.6, 5.2, 0.4, 0.4, 1.2, -0.1, 0.9, 2.6, 2.1, -1.7, 1.6, -0.7, 0.1, 1.9, 1.3, 1.5, 2.9, 2.5, 1.5, 2.0, 2.3, -0.6, 0.8, 41.8, 39.7, 4.4, 3.6, 5.2, 5.5, 1.9, 1.5, 2.9, 3.1, 2.5, 2.0, 2.3, 2.4, '$26,100,000 ', '$27,700,000 ', 2.6, 3.6, 0.73, 4.0, '$20,600,000 ', 4.6, '$23,400,000 ', 14.0, 7.9, 6.1, 12.5, 3.9, 5.0, 29.27, 7.0, 81.0, 230.0, 4.0, 29.0),
 (1978, 'NYK', 'Bob McAdoo', 26, 79, 3182, 22.0, 0.5670000000000001, None, 0.41200000000000003, 7.8, 24.7, 16.4, 13.4, 1.4, 2.0, 15.8, 26.1, None, 6.9, 4.0, 10.9, 0.165, None, 2.4, 0.8, 3.1, 4.1, 0.10400000000000001, 0.061, 22.0, 'mcadobo01', -0.47, 20005, 82, 0.0, 0.528, 333391, 0.518, 1.37, -0.01, 0.11, 0.75, 1.51, 3.62, '79.50%', 2.88, 0.53, -0.22, 3.4, 2.0, 2.7, 4.3, 0.1, 0.4, 1.5, -0.2, 0.8, 2.6, 2.0, 0.8, 1.3, -0.1, -1.3, 2.5, 1.4, 2.0, 3.3, 0.9, 1.5, 0.7, 1.0, 1.6, 0.8, 40.3, 38.3, 3.4, 2.7, 4.3, 4.5, 2.5, 2.0, 3.3, 3.5, 0.9, 0.7, 1.0, 1.0, '$21,800,000 ', '$22,600,000 ', 2.5, 3.0, 0.73, 3.6, '$18,500,000 ', 3.9, '$19,900,000 ', 11.6, 9.0, 2.6, 10.6, 3.6, 5.0, 26.36, 5.0, 81.0, 210.0, 4.0, 26.0),
 (1978, 'NJN', 'Bernard King', 21, 79, 3092, 17.3, 0.511, None, 0.27699999999999997, 7.9, 16.0, 11.8, 9.9, 1.7, 0.6, 14.3, 26.0, None, 2.6, 3.3, 5.9, 0.092, None, 1.0, 0.0, 0.9, 2.3, 0.040999999999999995, 0.051, 22.3, 'kingbe01', -4.89, 19905, 82, 0.0, 0.485, 332793, 0.478, -0.22, -0.38, 0.02, 0.76, 1.38, 1.54, '77.70%', 1.2, -3.01, -0.57, 1.0, 2.0, 0.8, 2.3, 0.1, 0.3, 1.2, 0.0, 0.7, 2.3, 1.8, -5.7, -1.2, -1.1, 0.8, 1.2, 1.4, 0.9, 2.2, -0.2, 1.5, -0.1, 0.1, 1.3, 0.8, 39.1, 37.3, 1.0, 0.8, 2.3, 2.4, 1.2, 0.9, 2.2, 2.3, -0.2, -0.1, 0.1, 0.1, '$12,200,000 ', '$12,600,000 ', 1.6, 1.3, 0.69, 2.3, '$11,900,000 ', 2.1, '$10,900,000 ', 6.2, 6.0, 0.2, 5.5, 2.8, 3.0, 21.16, 0.0, 79.0, 205.0, 3.0, 21.0),
 (1978, 'CHI', 'Artis Gilmore', 28, 82, 3067, 23.5, 0.604, None, 0.531, 11.3, 26.6, 19.0, 14.0, 0.6, 3.2, 19.1, 25.3, None, 7.8, 3.7, 11.5, 0.18, None, 3.2, 1.0, 4.2, 4.8, 0.122, 0.057999999999999996, 20.5, 'gilmoar01', -0.79, 19755, 82, 0.0, 0.524, 327657, 0.505, 2.58, -0.38, 0.22, 1.38, 1.18, 4.77, '77.60%', 3.7, 0.11, -0.21, 4.6, 2.1, 3.5, 5.1, 1.0, 0.5, 1.9, -0.5, 0.6, 3.4, 2.7, 1.2, 1.9, -0.1, -2.0, 3.3, 1.4, 2.6, 3.9, 1.2, 1.5, 0.9, 1.2, 2.1, 0.8, 37.4, 35.7, 4.6, 3.5, 5.1, 5.1, 3.3, 2.6, 3.9, 3.9, 1.2, 0.9, 1.2, 1.2, '$25,600,000 ', '$25,600,000 ', 1.9, 3.3, 0.73, 3.9, '$19,700,000 ', 4.8, '$24,000,000 ', 13.7, 10.6, 3.2, 12.8, 5.0, 5.0, 28.36, 6.0, 86.0, 240.0, 5.0, 28.0),
 (1978, 'DEN', 'David Thompson', 23, 80, 3025, 23.2, 0.578, None, 0.42200000000000004, 5.5, 7.7, 6.6, 19.3, 1.3, 1.7, 11.5, 26.8, None, 10.8, 1.9, 12.7, 0.20199999999999999, None, 4.6, -1.4, 3.2, 4.0, 0.172, 0.03, 23.7, 'thompda01', 0.75, 19830, 82, 0.0, 0.531, 329852, 0.517, 1.1, -0.29, 0.24, 2.12, 1.23, 4.15, '76.30%', 3.17, 3.43, -0.51, 3.6, 2.1, 2.8, 4.3, 0.6, 0.5, 3.8, -0.2, 0.6, 5.3, 4.0, 1.4, 2.5, -0.2, -0.6, 5.1, 1.4, 3.9, 5.2, -1.5, 1.5, -1.1, -0.9, 6.6, 0.8, 37.8, 36.0, 3.6, 2.8, 4.3, 4.4, 5.1, 3.9, 5.2, 5.3, -1.5, -1.1, -0.9, -0.9, '$21,800,000 ', '$22,400,000 ', 2.2, 3.0, 0.73, 3.6, '$18,500,000 ', 4.1, '$20,800,000 ', 11.6, 14.1, -2.4, 11.1, 1.6, 2.0, 23.56, 2.0, 76.0, 195.0, 2.0, 24.0),
 (1978, 'GSW', 'Rick Barry', 33, 82, 3024, 20.9, 0.509, None, 0.243, 2.5, 12.8, 7.5, 22.6, 2.4, 0.8, 10.7, 27.1, None, 5.9, 3.8, 9.7, 0.154, None, 2.5, 0.2, 2.8, 3.7, 0.094, 0.06, 24.2, 'barryri01', 0.35, 19780, 82, 0.0, 0.508, 336026, 0.507, 1.23, 0.61, 0.17, 0.3, 1.12, 3.26, '76.40%', 2.49, 1.22, -0.16, 3.1, 2.1, 2.4, 3.9, -0.2, 0.4, 2.5, 0.2, 0.6, 3.5, 2.7, -1.3, 2.3, -0.8, 1.6, 2.7, 1.4, 2.1, 3.4, 0.4, 1.5, 0.3, 0.5, 2.3, 0.8, 36.9, 35.2, 3.1, 2.4, 3.9, 3.9, 2.7, 2.1, 3.4, 3.4, 0.4, 0.3, 0.5, 0.5, '$19,900,000 ', '$19,900,000 ', 1.9, 2.6, 0.73, 3.3, '$17,000,000 ', 3.7, '$18,900,000 ', 10.5, 9.1, 1.4, 10.0, 2.2, 3.0, 33.85, 11.0, 79.0, 205.0, 2.0, 34.0),
 (1978, 'IND', 'Ricky Sobers', 25, 79, 3019, 15.4, 0.514, None, 0.32799999999999996, 2.9, 7.8, 5.3, 27.7, 2.5, 0.4, 20.1, 21.8, None, 2.4, 2.4, 4.8, 0.076, None, 0.8, -0.4, 0.4, 1.8, 0.038, 0.038, 17.4, 'soberri01', -2.13, 19830, 82, 0.0, 0.5, 335032, 0.49700000000000005, 1.37, 0.52, 0.29, -2.01, 1.27, 1.16, '76.10%', 0.88, 1.39, -0.79, 0.4, 2.1, 0.3, 1.8, 0.2, 0.4, 0.1, 0.3, 0.7, 1.6, 1.3, -1.2, 2.5, -0.8, -0.9, 0.9, 1.4, 0.6, 1.9, -0.5, 1.5, -0.4, -0.1, 1.3, 0.8, 38.2, 36.4, 0.4, 0.3, 1.8, 1.9, 0.9, 0.6, 1.9, 2.0, -0.5, -0.4, -0.1, -0.1, '$9,700,000 ', '$10,100,000 ', 1.8, 1.0, 0.66, 2.0, '$10,700,000 ', 1.6, '$8,500,000 ', 4.9, 5.2, -0.4, 4.2, 1.1, 1.0, 25.05, 2.0, 75.0, 198.0, 1.0, 25.0)]

In [128]:
## Delete data from the tables in the event that the queries are ran again and to avoid duplicate data

In [154]:
%%sql
DELETE from Team;
DELETE from Game;
DELETE from Stats;
DELETE from Season;
DELETE from Player

11 rows affected.
215 rows affected.
216 rows affected.
38 rows affected.
0 rows affected.

[]

## Insert data into the tables we have created from both csv files(imported and url)

In [155]:
%%sql 
INSERT INTO Team(TeamID, TeamName)
SELECT DISTINCT TeamID, TeamName
From NBAData;

INSERT INTO Game(GameNumber, TeamId, Minutes, Year)
SELECT DISTINCT GameID, Team.TeamID, Minutes, Year
FROM Team JOIN NBAData ON (NBAData.TeamID = Team.TeamID);


INSERT INTO Stats(Points, TeamID, ThreePts, FreeThrow, OffenseRebound, DefenseRebound, Home, Win)
SELECT DISTINCT Points, Team.TeamID, ThreePts, FreeThrow, OffensiveRebound, DefensiveRebound, Home, Win
From Team JOIN NBAData ON (NBAData.TeamID = Team.TeamID);

INSERT INTO Season(Year, TeamID)
SELECT DISTINCT Year, Team.TeamID
FROM NBAData Join Team ON (Team.TeamID = NBAData.TeamID);

INSERT INTO Player(PlayerName, TeamID, SeasonID, Age)
SELECT DISTINCT Player, Team.TeamID, Season.SeasonID, Age
FROM PlayerData JOIN Team ON (Team.TeamID = PlayerData.Tm)
            JOIN Season ON (Season.Year = PlayerData.year);

11 rows affected.
215 rows affected.
216 rows affected.
38 rows affected.
6526 rows affected.

[]

## To test out the Migrated Data, we created a few select queries

**Let's find out all players who played on the winning team of 2000**

In [139]:
%%sql
SELECT DISTINCT Player, Season.TeamID, Year
from Player JOIN Season ON (Player.TeamID=Season.TeamID)
where Season.Year = 2000
;

Done.

[(0, 'LAL', 2000),
 ('A.C. Green', 'LAL', 2000),
 ('Aaron McKie', 'LAL', 2000),
 ('Adam Morrison', 'LAL', 2000),
 ('Adrian Branch', 'LAL', 2000),
 ('Alan Hardy', 'LAL', 2000),
 ('Alex Blackwell', 'LAL', 2000),
 ('Andrew Bynum', 'LAL', 2000),
 ('Andrew Goudelock', 'LAL', 2000),
 ('Antawn Jamison', 'LAL', 2000),
 ('Anthony Brown', 'LAL', 2000),
 ('Anthony Miller', 'LAL', 2000),
 ('Anthony Peeler', 'LAL', 2000),
 ('Antonio Harvey', 'LAL', 2000),
 ('Benoit Benjamin', 'LAL', 2000),
 ('Billy Ray Bates', 'LAL', 2000),
 ('Billy Thompson', 'LAL', 2000),
 ('Bob McAdoo', 'LAL', 2000),
 ('Brad Holland', 'LAL', 2000),
 ('Brandon Bass', 'LAL', 2000),
 ('Brian Cook', 'LAL', 2000),
 ('Brian Grant', 'LAL', 2000),
 ('Brian Shaw', 'LAL', 2000),
 ('Bryon Russell', 'LAL', 2000),
 ('Butch Carter', 'LAL', 2000),
 ('Butch Lee', 'LAL', 2000),
 ('Byron Scott', 'LAL', 2000),
 ('Calvin Garrett', 'LAL', 2000),
 ('Carlos Boozer', 'LAL', 2000),
 ('Caron Butler', 'LAL', 2000),
 ('Cedric Ceballos', 'LAL', 2000),
 ('Chris Duhon', 'LAL', 2000),
 ('Chris Kaman', 'LAL', 2000),
 ('Chris Mihm', 'LAL', 2000),
 ('Christian Eyenga', 'LAL', 2000),
 ('Chuck Nevitt', 'LAL', 2000),
 ('Chucky Atkins', 'LAL', 2000),
 ('Chucky Brown', 'LAL', 2000),
 ('Clay Johnson', 'LAL', 2000),
 ('Cliff Robinson', 'LAL', 2000),
 ('Coby Karl', 'LAL', 2000),
 ('Corie Blount', 'LAL', 2000),
 ("D'Angelo Russell", 'LAL', 2000),
 ('Danny Schayes', 'LAL', 2000),
 ('Darius Johnson-Odom', 'LAL', 2000),
 ('Darius Morris', 'LAL', 2000),
 ('David Rivers', 'LAL', 2000),
 ('Demetrius Calip', 'LAL', 2000),
 ('Dennis Rodman', 'LAL', 2000),
 ('Derek Fisher', 'LAL', 2000),
 ('Derek Harper', 'LAL', 2000),
 ('Derek Strong', 'LAL', 2000),
 ('Derrick Caracter', 'LAL', 2000),
 ('Devean George', 'LAL', 2000),
 ('Devin Ebanks', 'LAL', 2000),
 ('Devin Green', 'LAL', 2000),
 ('Didier Ilunga-Mbenga', 'LAL', 2000),
 ('Don Ford', 'LAL', 2000),
 ('Doug Christie', 'LAL', 2000),
 ('Duane Cooper', 'LAL', 2000),
 ('Dwight Buycks', 'LAL', 2000),
 ('Dwight Howard', 'LAL', 2000),
 ('Dwight Jones', 'LAL', 2000),
 ('Earl Clark', 'LAL', 2000),
 ('Earl Jones', 'LAL', 2000),
 ('Ed Davis', 'LAL', 2000),
 ('Eddie Jones', 'LAL', 2000),
 ('Eddie Jordan', 'LAL', 2000),
 ('Elden Campbell', 'LAL', 2000),
 ('Elias Harris', 'LAL', 2000),
 ('Frank Brickowski', 'LAL', 2000),
 ('Frankie King', 'LAL', 2000),
 ('Fred Roberts', 'LAL', 2000),
 ('Gary Payton', 'LAL', 2000),
 ('George Lynch', 'LAL', 2000),
 ('George McCloud', 'LAL', 2000),
 ('Glen Rice', 'LAL', 2000),
 ('Greg Foster', 'LAL', 2000),
 ('Horace Grant', 'LAL', 2000),
 ('Ime Udoka', 'LAL', 2000),
 ('Ira Newble', 'LAL', 2000),
 ('Irving Thomas', 'LAL', 2000),
 ('Isaiah Rider', 'LAL', 2000),
 ('J.R. Reid', 'LAL', 2000),
 ('Jabari Brown', 'LAL', 2000),
 ('Jack Haley', 'LAL', 2000),
 ('Jamaal Wilkes', 'LAL', 2000),
 ('Jamal Sampson', 'LAL', 2000),
 ('James Edwards', 'LAL', 2000),
 ('James Worthy', 'LAL', 2000),
 ('Jannero Pargo', 'LAL', 2000),
 ('Jason Kapono', 'LAL', 2000),
 ('Javaris Crittenton', 'LAL', 2000),
 ('Jawann Oldham', 'LAL', 2000),
 ('Jay Vincent', 'LAL', 2000),
 ('Jeff Lamp', 'LAL', 2000),
 ('Jelani McCoy', 'LAL', 2000),
 ('Jeremy Lin', 'LAL', 2000),
 ('Jerome Henderson', 'LAL', 2000),
 ('Jerome Kersey', 'LAL', 2000),
 ('Jim Brewer', 'LAL', 2000),
 ('Jim Chones', 'LAL', 2000),
 ('Jim Jackson', 'LAL', 2000),
 ('Jodie Meeks', 'LAL', 2000),
 ('Joe Cooper', 'LAL', 2000),
 ('Joe Crispin', 'LAL', 2000),
 ('Joe Kleine', 'LAL', 2000),
 ('Joe Smith', 'LAL', 2000),
 ('John Celestand', 'LAL', 2000),
 ('John Salley', 'LAL', 2000),
 ('Jon Barry', 'LAL', 2000),
 ('Jordan Clarkson', 'LAL', 2000),
 ('Jordan Farmar', 'LAL', 2000),
 ('Jordan Hill', 'LAL', 2000),
 ('Josh McRoberts', 'LAL', 2000),
 ('Josh Powell', 'LAL', 2000),
 ('Julius Randle', 'LAL', 2000),
 ('Jumaine Jones', 'LAL', 2000),
 ('Kareem Abdul-Jabbar', 'LAL', 2000),
 ('Kareem Rush', 'LAL', 2000),
 ('Karl Malone', 'LAL', 2000),
 ('Keith Owens', 'LAL', 2000),
 ('Kendall Marshall', 'LAL', 2000),
 ('Kenny Carr', 'LAL', 2000),
 ('Kent Bazemore', 'LAL', 2000),
 ('Kevin McKenna', 'LAL', 2000),
 ('Kobe Bryant', 'LAL', 2000),
 ('Kurt Rambis', 'LAL', 2000),
 ('Kwame Brown', 'LAL', 2000),
 ('Lamar Odom', 'LAL', 2000),
 ('Laron Profit', 'LAL', 2000),
 ('Larry Drew', 'LAL', 2000),
 ('Larry Krystkowiak', 'LAL', 2000),
 ('Larry Nance Jr.', 'LAL', 2000),
 ('Larry Spriggs', 'LAL', 2000),
 ('Lester Conner', 'LAL', 2000),
 ('Lindsey Hunter', 'LAL', 2000),
 ('Lloyd Daniels', 'LAL', 2000),
 ('Lou Williams', 'LAL', 2000),
 ('Luke Walton', 'LAL', 2000),
 ('Magic Johnson', 'LAL', 2000),
 ('Manny Harris', 'LAL', 2000),
 ('MarShon Brooks', 'LAL', 2000),
 ('Marcelo Huertas', 'LAL', 2000),
 ('Mario Bennett', 'LAL', 2000),
 ('Mark Landsberger', 'LAL', 2000),
 ('Mark Madsen', 'LAL', 2000),
 ('Mark McNamara', 'LAL', 2000),
 ('Marty Byrnes', 'LAL', 2000),
 ('Matt Barnes', 'LAL', 2000),
 ('Maurice Carter', 'LAL', 2000),
 ('Maurice Evans', 'LAL', 2000),
 ('Maurice Lucas', 'LAL', 2000),
 ('Mel McCants', 'LAL', 2000),
 ('Metta World Peace', 'LAL', 2000),
 ('Michael Cooper', 'LAL', 2000),
 ('Mike Higgins', 'LAL', 2000),
 ('Mike McGee', 'LAL', 2000),
 ('Mike Penberthy', 'LAL', 2000),
 ('Mike Smrek', 'LAL', 2000),
 ('Milt Wagner', 'LAL', 2000),
 ('Mitch Kupchak', 'LAL', 2000),
 ('Mitch Richmond', 'LAL', 2000),
 ('Mychal Thompson', 'LAL', 2000),
 ('Myles Patrick', 'LAL', 2000),
 ('Nick Van Exel', 'LAL', 2000),
 ('Nick Young', 'LAL', 2000),
 ('Norm Nixon', 'LAL', 2000),
 ('Ollie Mack', 'LAL', 2000),
 ('Orlando Woolridge', 'LAL', 2000),
 ('Pau Gasol', 'LAL', 2000),
 ('Petur Gudmundsson', 'LAL', 2000),
 ('Ramon Sessions', 'LAL', 2000),
 ('Randolph Keys', 'LAL', 2000),
 ('Ray Tolbert', 'LAL', 2000),
 ('Reggie Jordan', 'LAL', 2000),
 ('Rick Fox', 'LAL', 2000),
 ('Robert Horry', 'LAL', 2000),
 ('Robert Sacre', 'LAL', 2000),
 ('Ron Boone', 'LAL', 2000),
 ('Ron Harper', 'LAL', 2000),
 ('Ronnie Lester', 'LAL', 2000),
 ('Ronnie Price', 'LAL', 2000),
 ('Ronny Turiaf', 'LAL', 2000),
 ('Rory Sparrow', 'LAL', 2000),
 ('Roy Hibbert', 'LAL', 2000),
 ('Ruben Patterson', 'LAL', 2000),
 ('Rumeal Robinson', 'LAL', 2000),
 ('Ryan Kelly', 'LAL', 2000),
 ('Sam Bowie', 'LAL', 2000),
 ('Sam Jacobson', 'LAL', 2000),
 ('Sam Perkins', 'LAL', 2000),
 ('Samaki Walker', 'LAL', 2000),
 ('Sasha Vujacic', 'LAL', 2000),
 ('Sean Rooks', 'LAL', 2000),
 ('Sedale Threatt', 'LAL', 2000),
 ('Shammond Williams', 'LAL', 2000),
 ('Shannon Brown', 'LAL', 2000),
 ("Shaquille O'Neal", 'LAL', 2000),
 ('Shawne Williams', 'LAL', 2000),
 ('Shea Seals', 'LAL', 2000),
 ('Smush Parker', 'LAL', 2000),
 ('Soumaila Samake', 'LAL', 2000),
 ('Spencer Haywood', 'LAL', 2000),
 ('Stanislav Medvedenko', 'LAL', 2000),
 ('Steve Blake', 'LAL', 2000),
 ('Steve Bucknall', 'LAL', 2000),
 ('Steve Mix', 'LAL', 2000),
 ('Steve Nash', 'LAL', 2000),
 ('Sun Yue', 'LAL', 2000),
 ('Swen Nater', 'LAL', 2000),
 ('Tarik Black', 'LAL', 2000),
 ('Terry Teagle', 'LAL', 2000),
 ('Theo Ratliff', 'LAL', 2000),
 ('Tierre Brown', 'LAL', 2000),
 ('Tony Bobbitt', 'LAL', 2000),
 ('Tony Brown', 'LAL', 2000),
 ('Tony Campbell', 'LAL', 2000),
 ('Tony Jackson', 'LAL', 2000),
 ('Tony Smith', 'LAL', 2000),
 ('Tracy Murray', 'LAL', 2000),
 ('Travis Knight', 'LAL', 2000),
 ('Trevor Ariza', 'LAL', 2000),
 ('Trevor Wilson', 'LAL', 2000),
 ('Trey Johnson', 'LAL', 2000),
 ('Troy Murphy', 'LAL', 2000),
 ('Tyronn Lue', 'LAL', 2000),
 ('Vander Blue', 'LAL', 2000),
 ('Vlade Divac', 'LAL', 2000),
 ('Vladimir Radmanovic', 'LAL', 2000),
 ('Von Wafer', 'LAL', 2000),
 ('Wayne Ellington', 'LAL', 2000),
 ('Wes Matthews', 'LAL', 2000),
 ('Wesley Johnson', 'LAL', 2000),
 ('Xavier Henry', 'LAL', 2000)]

**Let's find out the average age of players on the winning team in 1990**

In [140]:
%%sql 
SELECT AVG(AGE),TeamName, Season.Year
from Player JOIN Team ON (Player.TeamID=Team.TeamID)
            JOIN SEASON ON (Player.SeasonID=Season.SeasonID);

Done.

[(26.920931657983452, 'Warriors', 2016)]

**Let's find out how many times the Celtics has won a championship since 1980**

In [141]:
%%sql
SELECT COUNT(DISTINCT YEAR), TeamName
From Season JOIN Team ON (Team.TeamID=Season.TeamID)
Where Team.TeamID = 'BOS';

Done.

[(4, 'Celtics')]

**....and who has won the championships the most since 1980..**

In [142]:
%%sql
SELECT Count(Year), TeamName
From Season JOIN Team ON (Team.TeamID=Season.TeamID)
Group by TeamName
Order by Count(year) desc;

Done.

[(10, 'Lakers'),
 (6, 'Bulls'),
 (5, 'Spurs'),
 (4, 'Celtics'),
 (3, 'Heat'),
 (3, 'Pistons'),
 (2, 'Rockets'),
 (2, 'Warriors'),
 (1, 'Cavaliers'),
 (1, 'Mavericks'),
 (1, 'Sixers')]

**stats about the rockets championship games **

In [143]:
%%sql
SELECT TeamName, Points AS [Points Per Game], FreeThrow AS [Free Throws Per Game], (OffenseRebound+DefenseRebound) AS [TotalRebounds]
from Stats JOIN Team ON (Team.TeamID=Stats.TeamID)
Where Team.TeamID = "HOU";

Done.

[('Rockets', 85, 19, 49),
 ('Rockets', 83, 13, 38),
 ('Rockets', 93, 27, 47),
 ('Rockets', 82, 14, 33),
 ('Rockets', 84, 12, 42),
 ('Rockets', 86, 17, 38),
 ('Rockets', 90, 18, 33),
 ('Rockets', 120, 18, 41),
 ('Rockets', 117, 34, 38),
 ('Rockets', 106, 21, 46),
 ('Rockets', 113, 22, 48)]